### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#43] opened 2016-10-03 18:32 UTC
- [x] Use flexbox?
- [x] Specific names for classes used

**Comment by richford** [comment] 2016-10-21 12:34
#41 addresses both of these but the issue is not yet closed because there is a bug that does not allow narrowing the 3d-brain div. It'll `flex-grow` but never wants to `flex-shrink`.

**Comment by richford** [comment] 2016-11-08 18:45
Addressed by #61

**Closed as completed by richford** 2016-11-08 18:45 UTC
